name: less_node
version: 0.2.1
author: Adalberto Lacruz <adalberto.lacruz@gmail.com>
description: Less transformer wrapped over nodejs. Build .css files from .less files.
homepage: https://github.com/AdalbertoLacruz/less_node
dependencies:
  barback: '>=0.13.0 <0.16.0'
  utf: '>=0.9.0 <0.12.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.12.0'
